### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by WhatAShot** [ZhangTP1996/TapTap#2]
Congratulations on the fantastic work! As a good benchmark, it would be helpful if the collected 450 datasets can be available. Will  you make the datasets and the corresponding codes open?

**Comment by ZhangTP1996** [comment]
Thank you for your interest in our work! The collected datasets have been uploaded to huggingface: https://huggingface.co/datasets/ztphs980/taptap_datasets/. Regarding your query about "the corresponding codes," could you please clarify what specifically you are referring to?

**Comment by WhatAShot** [comment]
Thank you very much. The dataset collection is helpful. The “corresponding codes” mean the code to utilize and pre-process the datasets, but it doesnt matter.
