### ISSUE TITLE
blank items

### ISSUE THREAD

**Issue by Travisma2233** [ZhangTP1996/TapTap#4]
Hello, may I ask why there are a lot of blank items in the data I generated？
![image](https://github.com/ZhangTP1996/TapTap/assets/83893812/563e5688-2e35-49e9-ae72-ebce92f0b31b)

**Comment by ZhangTP1996** [comment]
The program should print the generated text (in line 234 of taptap.py), could you please show what is printed? It should help diagnose the reason. One possible reason is that the number of steps is too small so that the model has not yet fit on this table.
